version: '3.1'

services:
  mysql:
    container_name: mysql_alkemy
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: alkemy
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    